export interface RequestForms {
    request_form_id? : string,
    control_number : number,
    patients_name? : string,
    representative_name? : string,
    address? : string,
    request_provided? : string,
    contact_number? : number | null,
    provider_id? : number,
    account_id? : number,
    amount? : number | null,
    request_date? : Date | null,
    hospital_name? : string,
    is_cancel? : boolean,
    cancel_information? : string,
}
